version: "3.3"

services:
  
  dbt: 
    build:
      context: ./dbt
    depends_on:
      - clickhouse
    links:
      - clickhouse
    ports:
      - 8001:8001

   

  clickhouse:
    image: yandex/clickhouse-server:21.7.11
    ports:
      - 8123:8123


  tabix:
    image: spoonest/clickhouse-tabix-web-client
    ports:
      - "5051:80"
    depends_on:
      - clickhouse
    links:
      - clickhouse
         